### ISSUE TITLE
HID BLE Keyboard example compatibility matrix

### ISSUE THREAD

**Issue by InTEGr8or** [cypresssemiconductorco/mtb-examples-CYW920820EVB-02-btsdk-hid#1]
**Have you looked for an answer?**

I've checked the ModusToolbox User Guide, wiced_btsdk documentation, the README for this project, google searches and Cypress youtube videos

**Question/Issue**:

I am coming from the PSoC Creator environment and trying to migrate my existing **HID BLE Keyboard** project from there to any of these new BLE modules, preferably with Bluetooth 5 and castellation pads on the package.

This example lists these boards and I am trying to use the CYBT-213043-EVAL

* CYW20819A1 chip: CYW920819EVB-02, CYBT-213043-MESH, CYBT-213043-EVAL, CYW920819REF-KB-01
* CYW20820A1 chip: CYW920820EVB-02, CYW989820EVB-01
* CYW20721B2 chip: CYW920721B2EVK-02, CYW920721B2EVK-03, CYW920721M2EVK-02, CYBT-423060-EVAL, CYBT-483062-EVAL, CYBT-413061-EVAL
* CYW20719B2 chip: CYW920719B2Q40EVB-01, CYBT-423054-EVAL, CYBT-413055-EVAL, CYBT-483056-EVAL
* CYW20706A2 chip: CYW920706WCDEVAL, CYBT-353027-EVAL, CYBT-343026-EVAL
* CYW20735B1 chip: CYW920735Q60EVB-01
* CYW20835B1 chip: CYW920835REF-RCU-01
* CYW43012C0 chip: CYW9M2BASE-43012BT, CYW9M2BASE-43012BT20

When I try to import the example the only devices available are:

* CYBT-243053-02
* CYBT-253059-02
* CYW20820A1KFB1G
* CYW20820A1KFBG
* CYW89820BWMLG

And the first two of those have very limited information. I'm not even sure if they are available yet.

**Context**

I'm using a CYBT-213043-EVAL, but I have others and would use whatever is best for BLE HID example.

**Where did you expect to find the answer?**

I would like to know if there is:
* any compatibility matrix that would map an BLE HID Keyboard example to a list of products it will work with
* or, any link to instructions on how to map this example to more common devices.

I would think that these examples would be designed to work with several common devices, or that there would be some way to map them over to other devices, even by a manual process with refactoring.

###### THANKS!

Thanks for any info.

**Comment by AnjanaMuralidharan** [comment]
Hi,

We do have HID examples available in MTB. 
As of now its under few of the chipset as mentioned in the Technical brief here: https://community.cypress.com/docs/DOC-21253
Please have a look.

Regards,
Anjana
